### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by R4xx4r** [Domi236/music_player#2]
Ich weiß bzw denke du wolltest es nur schnell mal pushen das ichs seh, aber da gleich mal 2,3 Dinge :smile: 

**1) Warum wolltest dus erst da pushen und das Ding ist nicht schon von haus aus auf git ?**

**2) Dateinamen einheitlich halten nicht einmal camelCase und einmal snake case usw**
![cleanup01](https://user-images.githubusercontent.com/7009482/67901074-235c5380-fb66-11e9-8558-a14d2dcfbe3e.png)

**3) Sind das echt alles Datein die du in dem Projekt brauchst?** 
Der Folder namens `extra_shit_in_work` klingt eher weniger nach nem Ordner der in nem projekt sein sollte (stell dir vor ich wäre der kunde nur ohne diesmal mails und co :wink: 

**4) Readme ist leider wichtig**
siehe #1

**Comment by Domi236** [comment]
Das eine is file is der name meiner datenbank, das mit extra shit is nur für mich codesnippets

**Comment by Domi236** [comment]
War bis jetzt noch nicht so nötig hab immer nur am leptop unterwegs gearbeitet

**Comment by R4xx4r** [comment]
> Das eine is file is der name meiner datenbank,

Ich weiss was es ist, du hast die anforderung nicht verstanden :D
Es geht ums naming warum heisst eines `updateDetail` (camelCase) und das andere `boss_music` (snake_case). sprich warum mischt du und machst es ned einheitlich ?


>  das mit extra shit is nur für mich codesnippets

jap das hab ich mir gedacht, nur was hat das mit dem projekt zu tun ?
suaberkeit ist wichtig ;)


> War bis jetzt noch nicht so nötig hab immer nur am leptop unterwegs gearbeitet

dann ahst du den sinn einer versionierung nicht verstanden. es geht nicht darum sachen zu teilen sondenr sie dokumentiert zu haben. du arbeitest 40h an nem projekt und kommst dann drauf da is was falsch ... ab wann denn ? du musst alles debuggen und kannst ned versionen anschauen usw ...
vor allem wenns ein privates repo is is noch mehr wurscht (sollte dir aber auch so wurscht sein ;) )
